
name: Go

on: [push, pull_request]

jobs:

  losses:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Python3
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: pip install -r requirements.txt
      
    - name: Run Pytest
      run: cd tests/ && pytest -v
